import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerGetSummary } from "./get-summary.js";
import { registerGetOhlcv } from "./get-ohlcv.js";
import { registerGetSearch } from "./get-search.js";
import { registerGetSchema } from "./get-schema.js";
import { registerGetWatchlist } from "./get-watchlist.js";
import { registerGetWatchlistChanges } from "./get-watchlist-changes.js";
import { registerAddToWatchlist } from "./add-to-watchlist.js";
import { registerRemoveFromWatchlist } from "./remove-from-watchlist.js";
import { registerGetAccount } from "./get-account.js";
import { registerCreateWebhook } from "./create-webhook.js";
import { registerListWebhooks } from "./list-webhooks.js";
import { registerDeleteWebhook } from "./delete-webhook.js";
import { registerUpdateWebhook } from "./update-webhook.js";
import { registerListWebhookDeliveries } from "./list-webhook-deliveries.js";
import { registerListScreeners } from "./list-screeners.js";
import { registerCreateScreener } from "./create-screener.js";
import { registerUpdateScreener } from "./update-screener.js";
import { registerDeleteScreener } from "./delete-screener.js";

export function registerAllTools(server: McpServer, apiKey: string) {
  registerGetSummary(server, apiKey);
  registerGetOhlcv(server, apiKey);
  registerGetSearch(server, apiKey);
  registerGetSchema(server, apiKey);
  registerGetWatchlist(server, apiKey);
  registerGetWatchlistChanges(server, apiKey);
  registerAddToWatchlist(server, apiKey);
  registerRemoveFromWatchlist(server, apiKey);
  registerGetAccount(server, apiKey);
  registerCreateWebhook(server, apiKey);
  registerListWebhooks(server, apiKey);
  registerDeleteWebhook(server, apiKey);
  registerUpdateWebhook(server, apiKey);
  registerListWebhookDeliveries(server, apiKey);
  registerListScreeners(server, apiKey);
  registerCreateScreener(server, apiKey);
  registerUpdateScreener(server, apiKey);
  registerDeleteScreener(server, apiKey);
}
